### PR TITLE
Create domain work around for federated users

### PR DESCRIPTION
**Pull request by edtubillara**
I filed a bug here: https://bugs.launchpad.net/horizon/+bug/1627062

Federated admins and users have trouble using horizon because
they are in the federated domain. They are not able to list/create projects,
groups, and users because horizon filters by domain. This code
will see if the user is federated and then set the domain to
the current scoped project's domain.

### CODE REVIEW

**Comment by lihkin213** [comment]
I do not see the associated change to the federation.yml in keystone-setup role to remove the setting federated_domain_id from keystone.conf. We can leave it in for older envs but should not add it to the new envs.

**Comment by edtubillara** [comment]
made the PR here:
https://github.com/blueboxgroup/ursula/pull/2214

**Comment by lihkin213** [comment]
Thanks!

**Comment by lihkin213** [comment]
LGTM

**Review by lihkin213 — APPROVED** [review]

**Pull request merged**
